package KorneaDonörveAlıcıYönetimUygulaması;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Osman Furkan Erkan
 */

import KorneaDonörveAlıcıYönetimUygulaması.AnaSayfaForm;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import java.util.List;

public class DonörForm extends javax.swing.JFrame {

    public DonörForm() {
        initComponents();
        this.setTitle("Donör Yönetim Paneli");
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        tabloyuYenileDonor();
        
        txtAdSoyad.setText(""); 
    }

    private void tabloyuYenileDonor() {
        DefaultTableModel model = (DefaultTableModel) jTableDonor.getModel();
        model.setRowCount(0);

        DonörYöneticisi yonetici = new DonörYöneticisi();
        List<Donör> donorler = yonetici.tumDonorleriListele();

        for (Donör d : donorler) {
            String lamelYazisi = "";
            
            if (d.getPkUygunluk() == 2) {
                Integer tip = d.getLamellerTip();
                if (tip != null) {
                    if (tip == 1) {
                        lamelYazisi = "ön Lameller";
                    } else if (tip == 2) {
                        lamelYazisi = "arka Lamel";
                    }
                }
            }

            model.addRow(new Object[]{
                d.getId(),
                d.getAdSoyad(),
                d.getDogumYili(),
                (d.getCinsiyet() == 0 ? "erkek" : "kadın"),
                d.getEndotelSayisi(),
                (d.getPkUygunluk() == 0 ? "evet" : "hayır"),
                lamelYazisi
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDonor = new javax.swing.JTable();
        txtAdSoyad = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        txtDogumYili = new java.awt.TextField();
        cbCinsiyet = new javax.swing.JComboBox<>();
        txtEndotel = new java.awt.TextField();
        cbPkUygunluk = new javax.swing.JComboBox<>();
        cbLamellerTip = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("     Donör  Yönetim Sayfası");

        jTableDonor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "İsim", "Yaş", "Cinsiyet", "Endotel Sayısı", "PK uygunluk", "Lameller Tip"
            }
        ));
        jScrollPane1.setViewportView(jTableDonor);

        button1.setLabel("Donör ekle");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("Donör sil");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jButton1.setText("Anasayfaya Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label4.setText("İsim Soyisim : ");

        label5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label5.setText("Yıl :");

        label6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label6.setText("Cinsiyet :");

        label7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label7.setText("Endotel Sayısı :");

        label8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label8.setText("Lameller Tipi :");

        label9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label9.setText("PK Uygunluk :");

        cbCinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "erkek", "kadın" }));

        txtEndotel.setName("txtEndotel"); // NOI18N

        cbPkUygunluk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "evet", "hayır" }));

        cbLamellerTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ön lameller", "arka lameller", "" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(269, 269, 269)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDogumYili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCinsiyet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEndotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPkUygunluk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbLamellerTip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDogumYili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEndotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbPkUygunluk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLamellerTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
   
        String isim = txtAdSoyad.getText().trim();
        String yilStr = txtDogumYili.getText().trim();

        List<String> eksikAlanlar = new ArrayList<>();
        if (isim.isEmpty()) {
            eksikAlanlar.add("Donör Adı ve Soyadı");
        }
        if (yilStr.isEmpty()) {
            eksikAlanlar.add("Doğum Yılı");
        }

        if (!eksikAlanlar.isEmpty()) {
            String mesaj = "Lütfen aşağıdaki alanları doldurunuz:\n\n- " + String.join("\n- ", eksikAlanlar);
            JOptionPane.showMessageDialog(this, mesaj, "Eksik Bilgi", JOptionPane.WARNING_MESSAGE);
            return;
        }

     
        int yil = 0;
        try {
            yil = Integer.parseInt(yilStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Doğum yılı geçersiz! Lütfen sadece sayı giriniz (Örn: 1990).", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

       
        Integer endotel = null;
        String endotelStr = txtEndotel.getText().trim();

        if (!endotelStr.isEmpty()) {
            try {
                endotel = Integer.parseInt(endotelStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Endotel sayısı sadece rakam olmalıdır!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }


        try {        
            int cinsiyet;
            if (cbCinsiyet.getSelectedItem().toString().equalsIgnoreCase("erkek")) {
                cinsiyet = 0;
            } else {
                cinsiyet = 1;
            }

            int pkUygun;
            if (cbPkUygunluk.getSelectedItem().toString().equalsIgnoreCase("evet")) {
                pkUygun = 0;
            } else {
                pkUygun = 1;
            }

            Integer lamel = null;
            if (cbLamellerTip.getSelectedItem() != null) {
                String secimYazisi = cbLamellerTip.getSelectedItem().toString();

                if (secimYazisi.contains("Ön")) {
                    lamel = 1;
                } else if (secimYazisi.contains("Arka")) {
                    lamel = 2;
                }
            }


            Donör yeniDonor = new Donör();
            yeniDonor.setAdSoyad(isim);
            yeniDonor.setDogumYili(yil);
            yeniDonor.setCinsiyet(cinsiyet);
            yeniDonor.setEndotelSayisi(endotel);
            yeniDonor.setPkUygunluk(pkUygun);
            yeniDonor.setLamellerTip(lamel);


            DonörYöneticisi yonetici = new DonörYöneticisi();
            yonetici.yeniDonörEkle(yeniDonor);

            JOptionPane.showMessageDialog(this, "Donör başarıyla eklendi.");

            txtAdSoyad.setText("");
            txtDogumYili.setText("");
            txtEndotel.setText("");
            tabloyuYenileDonor();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Beklenmeyen bir hata oluştu: " + e.getMessage());
        }
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        int seciliSatir = jTableDonor.getSelectedRow();
        if (seciliSatir == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen silmek için bir donör seçin.");
            return;
        }
        int donorId = Integer.parseInt(jTableDonor.getValueAt(seciliSatir, 0).toString());

        int secim = JOptionPane.showConfirmDialog(this, 
                "Seçilen donör kaydını silmek istediğinize emin misiniz?", 
                "Silme Onayı", 
                JOptionPane.YES_NO_OPTION,     
                JOptionPane.WARNING_MESSAGE);  

        if (secim == JOptionPane.YES_OPTION) {
            DonörYöneticisi yonetici = new DonörYöneticisi();
            yonetici.donorSil(donorId);
            JOptionPane.showMessageDialog(this, "Donör başarıyla silindi.");
            tabloyuYenileDonor();

        }
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AnaSayfaForm().setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
   
    com.formdev.flatlaf.FlatLightLaf.setup(); 

   
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new DonörForm().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JComboBox<String> cbCinsiyet;
    private javax.swing.JComboBox<String> cbLamellerTip;
    private javax.swing.JComboBox<String> cbPkUygunluk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDonor;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField txtAdSoyad;
    private java.awt.TextField txtDogumYili;
    private java.awt.TextField txtEndotel;
    // End of variables declaration//GEN-END:variables
}
