package KorneaDonörveAlıcıYönetimUygulaması;


import KorneaDonörveAlıcıYönetimUygulaması.AnaSayfaForm;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;



public class eslestirmeForm extends javax.swing.JFrame {
    Eslestirme eslestirmeMotoru = new Eslestirme();
    DonörYöneticisi donorYoneticisi = new DonörYöneticisi();
    HastaYoneticisi hastaYoneticisi = new HastaYoneticisi();

    public eslestirmeForm() {
        initComponents();
        this.setTitle("Hasta-Donör Eşleşim Yönetim Paneli");
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        donörleriYukleComboBox();

        List<Hasta> tumHastalar = hastaYoneticisi.tumHastalariListele();

        tabloyuDoldur(tumHastalar);

    }
    List<Donör> hafizadakiDonorler = new ArrayList<>();
    private void donörleriYukleComboBox() {

        hafizadakiDonorler = donorYoneticisi.tumDonorleriListele();
        jComboBox1.removeAllItems();

        for(Donör d : hafizadakiDonorler){          

            jComboBox1.addItem(d.toString()); 

        }
    }
   
    private void hastalariYukleJTable(List<Hasta> gelenListe) {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        for(Hasta h : gelenListe) {            
            String goz;

        if (h.getPkpAdayiGoz() == 1) {
            goz = "Sağ";
        } else {
            goz = "Sol";
        }

        String aciliyet;

        if (h.getLegalKorluk() == 1) {
            aciliyet = "Körlük";
        } else {
            aciliyet = "Normal";
        }

           
        
            model.addRow(new Object[]{
                h.getId(),
                h.getAdSoyad(),
                h.getYas(),
                goz, 
                aciliyet, 
                h.getPrimerHastalik()
            });
        }
    }
    
    private void tabloyuDoldur(List<Hasta> gelenListe){

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0); 
        for(Hasta h : gelenListe) {            

            String goz = (h.getPkpAdayiGoz() == 1 ? "Sağ" : "Sol");
            String aciliyet = (h.getLegalKorluk() == 1 ? "ACİL (Körlük)" : "Normal");


            model.addRow(new Object[]{
                h.getId(),
                h.getAdSoyad(),
                h.getYas(),
                goz, 
                aciliyet, 
                h.getPrimerHastalik()

            });

        }

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "AD SOYAD", "YAŞ", "GÖZ", "ACİLİYET", "ENDİKASYON", "ÖNCELİK PUANI"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        button1.setLabel("Eşleştir");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Eşleşim Sonuç Sayfası");

        jButton1.setText("Anasayfaya Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(343, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        Object secilenNesne = jComboBox1.getSelectedItem(); // Senin kodda adı jComboBox1 idi
        if (secilenNesne == null) {
            JOptionPane.showMessageDialog(this, "Lütfen listeden bir donör seçin!");
            return;
        }

        Donör seciliDonor = (Donör) secilenNesne;
        List<Hasta> siraliHastalar = eslestirmeMotoru.sirala(seciliDonor);

        hastalariYukleJTable(siraliHastalar);

        JOptionPane.showMessageDialog(this, "Eşleştirme tamamlandı! Liste puana göre sıralandı.");
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AnaSayfaForm().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

   
    public static void main(String args[]) {
    
        com.formdev.flatlaf.FlatLightLaf.setup(); 

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eslestirmeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
