package cornea.donor.recipient.management;


import cornea.donor.recipient.management.MainForm;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;



public class MatchingForm extends javax.swing.JFrame {
    Matching eslestirmeMotoru = new Matching();
    DonorManager donorYoneticisi = new DonorManager();
    PatientManager hastaYoneticisi = new PatientManager();

    public MatchingForm() {
        initComponents();
        try {
            java.net.URL iconURL = getClass().getResource("/images/cropped-Limbustem-1-1.jpeg");
            if (iconURL != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(iconURL);
                this.setIconImage(icon.getImage());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.setTitle("Hasta-Donör Eşleşim Yönetim Paneli");    
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        donörleriYukleComboBox();

        List<Patient> tumHastalar = hastaYoneticisi.tumHastalariListele();

        tabloyuDoldur(tumHastalar);

    }
    List<Donor> hafizadakiDonorler = new ArrayList<>();
    private void donörleriYukleComboBox() {

        hafizadakiDonorler = donorYoneticisi.tumDonorleriListele();
        jComboBox1.removeAllItems();

        for(Donor d : hafizadakiDonorler){          

            jComboBox1.addItem(d.toString()); 

        }
    }
   
    private void hastalariYukleJTable(List<Patient> gelenListe) {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        for(Patient h : gelenListe) {            
            String goz;

        if (h.getPkpAdayiGoz() == 1) {
            goz = "Sağ";
        } else {
            goz = "Sol";
        }

        String aciliyet;

        if (h.getLegalKorluk() == 1) {
            aciliyet = "Körlük";
        } else {
            aciliyet = "Normal";
        }
        
            model.addRow(new Object[]{
                h.getId(),
                h.getAdSoyad(),
                h.getYas(),
                goz, 
                aciliyet, 
                h.getPrimerHastalik()
            });
        }
    }
    
    private void tabloyuDoldur(List<Patient> gelenListe){

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0); 
        for(Patient h : gelenListe) {            

            String goz = (h.getPkpAdayiGoz() == 1 ? "Sağ" : "Sol");
            String aciliyet = (h.getLegalKorluk() == 1 ? "ACİL (Körlük)" : "Normal");


            model.addRow(new Object[]{
                h.getId(),
                h.getAdSoyad(),
                h.getYas(),
                goz, 
                aciliyet, 
                h.getPrimerHastalik()

            });

        }

    } 
    // --- ALPER HOCA'NIN İSTEDİĞİ RASTGELE (MOCK ML) TURNUVA ALGORİTMASI ---
    private List<Patient> rastgeleTurnuvaIleTop20Sec(List<Patient> tumHastalar) {
        List<Patient> havuz = new ArrayList<>(tumHastalar); 
        List<Patient> top20Listesi = new ArrayList<>();
        java.util.Random random = new java.util.Random();

        int secilecekKisiSayisi = Math.min(20, havuz.size());

        for (int i = 0; i < secilecekKisiSayisi; i++) {
            Patient suAnkiSampiyon = havuz.get(0);

            for (int j = 1; j < havuz.size(); j++) {
                Patient rakip = havuz.get(j);
                
                int modelKarari = random.nextInt(2); 
                
                if (modelKarari == 1) {
                    suAnkiSampiyon = rakip; 
                }
            }

            top20Listesi.add(suAnkiSampiyon);
            havuz.remove(suAnkiSampiyon);
        }

        return top20Listesi;
    }
    // ------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "AD SOYAD", "YAŞ", "GÖZ", "ACİLİYET", "ENDİKASYON", "ÖNCELİK PUANI"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        button1.setLabel("Eşleştir");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Eşleşim Sonuç Sayfası");

        jButton1.setText("Anasayfaya Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(343, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        int seciliIndex = jComboBox1.getSelectedIndex(); 
        
        if (seciliIndex == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen listeden bir donör seçin!");
            return;
        }

        Donor seciliDonor = hafizadakiDonorler.get(seciliIndex);
        
        List<Patient> tumHastalar = hastaYoneticisi.tumHastalariListele();
        
        List<Patient> top20Hastalar = rastgeleTurnuvaIleTop20Sec(tumHastalar);

        hastalariYukleJTable(top20Hastalar);

        JOptionPane.showMessageDialog(this, "Eşleştirme Simülasyonu Tamamlandı!\nRastgele turnuva ile en uygun 20 hasta belirlendi.");
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MainForm().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

   
    public static void main(String args[]) {
    
        com.formdev.flatlaf.FlatLightLaf.setup(); 

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatchingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
